# Simple 1 hidden layer neural-network

### Column three is always one, if either of columns 1 or 2 is 1, then the output is also 1. This is considered to be a nonlinear pattern because there isn't direct one2one relationship between columns. 
### Instead one2one relationship between the combination of the colums!!


In [1]:
import numpy as np

In [2]:
def sigmoid(x, deriv=False):
    # sigmoid function used for cost function.
    # it maps x features to [0, 1] output
    if deriv:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

In [3]:
# input data
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])
# output data
y = np.array([[0],
              [1],
              [1],
              [0]])

In [4]:
np.random.seed(1)  # having deterministic random values everytime we run the program

In [5]:
# Synapsis for connecting the neurons
# Also initializing random weights at mean at 0
syn0 = 2 * np.random.random((3, 4)) - 1
syn1 = 2 * np.random.random((4, 1)) - 1

In [6]:
# training
num_of_training = 10**5
for num in range(num_of_training):
    # Forward propogation: calculating layer_1 (hidden layer) values from the input and weights
    layer_0 = X
    layer_1 = sigmoid(np.dot(layer_0, syn0))
    if num == 0:
        print(layer_1)
    
    # Forward propogation: calculating layer_2 (output layer) from hidden layer and its weights
    layer_2 = sigmoid(np.dot(layer_1, syn1))
    # How much did we miss? Training error. 
    layer_2_error = y - layer_2
    
    if num % (num_of_training / 10) == 0:
        print('Mean Error: {}'.format(np.mean(np.abs(layer_2_error))))
        print('### layer_1 ###')
        print(layer_1)
        
    layer_2_delta = layer_2_error * sigmoid(layer_2, deriv=True)
    # This is the back-propogation. Calculating the layer_1 error
    # from the 'confidence weighted error'
    layer_1_error = layer_2_delta.dot(syn1.T)
    layer_1_delta = layer_1_error * sigmoid(layer_1, deriv=True)
    
    # update weights
    syn1 += layer_1.T.dot(layer_2_delta)
    syn0 += layer_0.T.dot(layer_1_delta)
    
print('End of training')
print(layer_2)

[[0.44856632 0.51939863 0.45968497 0.59156505]
 [0.28639589 0.32350963 0.31236398 0.51538526]
 [0.40795614 0.62674606 0.23841622 0.49377636]
 [0.25371248 0.42628115 0.14321233 0.41732254]]
Mean Error: 0.4964100319027255
### layer_1 ###
[[0.44856632 0.51939863 0.45968497 0.59156505]
 [0.28639589 0.32350963 0.31236398 0.51538526]
 [0.40795614 0.62674606 0.23841622 0.49377636]
 [0.25371248 0.42628115 0.14321233 0.41732254]]
Mean Error: 0.008584525653247153
### layer_1 ###
[[6.39794692e-01 1.37097918e-01 9.17995038e-01 9.94721470e-01]
 [2.05869639e-01 6.35412465e-04 1.84354882e-02 8.85392478e-01]
 [9.90358451e-01 8.73947201e-01 2.50298778e-02 7.89794557e-01]
 [9.37468194e-01 2.69966253e-02 4.30709360e-05 1.33471161e-01]]
Mean Error: 0.0057894598625078085
### layer_1 ###
[[6.76071621e-01 1.28168162e-01 9.21470647e-01 9.95877626e-01]
 [1.88772093e-01 5.21962936e-04 1.76602176e-02 8.90030167e-01]
 [9.93442489e-01 8.83064272e-01 2.38921162e-02 8.11403421e-01]
 [9.44105922e-01 2.61256437e-02 3.

In [11]:
layer_2_delta.shape

(4, 1)

In [8]:
layer_0.shape, syn0.shape

((4, 3), (3, 4))